[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[build.environment]
  REACT_APP_API_URL = "https://taskflow-backend.onrender.com"
  REACT_APP_DEFAULT_AVATAR = "https://www.w3schools.com/howto/img_avatar.png"

[[redirects]]
  from = "/talentosp-front-back-clase5/login"
  to = "/talentosp-front-back-clase5/index.html"
  status = 200

[[redirects]]
  from = "/talentosp-front-back-clase5/register"
  to = "/talentosp-front-back-clase5/index.html"
  status = 200

[[redirects]]
  from = "/talentosp-front-back-clase5/users"
  to = "/talentosp-front-back-clase5/index.html"
  status = 200

[[redirects]]
  from = "/talentosp-front-back-clase5/projects"
  to = "/talentosp-front-back-clase5/index.html"
  status = 200

[[redirects]]
  from = "/talentosp-front-back-clase5/*"
  to = "/talentosp-front-back-clase5/index.html"
  status = 200
